# config.yaml

train_path: '/data/ephemeral/input/data/train/'
eval_path: '/data/ephemeral/input/data/eval/'
save: 'model.pt'
dataset: 'train_ratings.csv'

seed: 42
heldout_users: 3000

lr: 0.001
epochs: 20
wd: 0.0
batch_size: 500
total_anneal_steps: 200000
anneal_cap: 0.2
log_interval: 100
